workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 60
    scripts:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
